name: Deploy Protobuf Docs

on:
  push:
    branches:
      - proto-summary-test
    paths:
      - 'sdks-and-apis/protobuf-markdowns/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Copy Protobuf Markdown Files
        run: |
          mkdir -p public
          cp -r sdks-and-apis/protobuf-markdowns/* public/

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
